services:
  - type: web
    name: coverflow-amf
    env: node
    buildCommand: |
      export NODE_OPTIONS="--max-old-space-size=4096"
      apt-get update && apt-get install -y libheif-dev libvips-dev
      cd packages/coverflow && npm ci --production
    startCommand: cd packages/coverflow && npm start
    disk:
      name: coverflow-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
      - key: DATA_DIR_PATH
        value: /var/data
      - key: DATA_SYNC_PROVIDER
        value: gcs
      - key: DATA_SYNC_PREFIX
        value: admin-data
      - key: DATA_SYNC_FILES
        value: covers.json,assets.json